name: Execução Diário do Robô

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispath:

jpbs:
  exeutar:
    runs-on: ubutu-latest

    steps:
      - name: clonar repositório
        uses: actions/checkout@v3

      - name: Commit do relatório
        run: |
            git conf user.name 'github-actions'
            git add dados/relatorio.csv
            git commit -m 'Atualização diaria'
            git push
        env:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} 
